
CREATE TABLE Static_BB_BranchCode (
    BranchNumber INT PRIMARY KEY,
    BranchName NVARCHAR(255),
    FI_Code INT,
    FI_BranchCode INT NULL
);

INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4101, N'AGRABAD ', 41, 1);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4125, N'ANDERKILLA ', 41, 33);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4135, N'ASHUGANJ ', 41, 13);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4046, N'AUSTOGRAM ', 41, 112);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4130, N'BAHADDARHAT ', 41, 39);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4033, N'BANANI ', 41, 102);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4016, N'BANDURA ', 41, 232);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4141, N'BANSKHALI ', 41, 47);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4321, N'BARISAL ', 41, 25);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4034, N'BASHUNDHARA ', 41, 103);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4218, N'BENAPOLE ', 41, 457);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4007, N'BHAIRAB BAZAR ', 41, 21);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4039, N'BHULTA ', 41, 107);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4129, N'BOALKHALI ', 41, 38);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4018, N'BOARD BAZAR ', 41, 301);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4201, N'BOGRA ', 41, 31);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4113, N'BOROIKANDI ', 41, 11);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4134, N'BRAHMANBARIA ', 41, 12);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4025, N'CARD DIVISION', 41, 18);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4110, N'CDA AVENUE ', 41, 7);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4133, N'CHAKARIA ', 41, 84);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4132, N'CHANDPUR ', 41, 90);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4026, N'CHANDRA ', 41, 302);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4204, N'CHAPAI NAWABGANJ ', 41, 641);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4139, N'CHATURI ', 41, 23);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4136, N'CHAUMUHANI ', 41, 121);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4107, N'CHAWK BAZAR ', 41, 35);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4119, N'CHHATAK ', 41, 87);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4131, N'COMILLA ', 41, 76);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4108, N'COX'S BAZAR ', 41, 85);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4111, N'DARGAHGATE ', 41, 8);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4123, N'DEWANHAT ', 41, 44);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4021, N'DHANMONDI ', 41, 235);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4208, N'DINAJPUR ', 41, 693);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4105, N'E. P. Z. ', 41, 5);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4051, N'FARIDPUR ', 41, 111);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4137, N'FENI ', 41, 88);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4114, N'GARDEN TOWER ', 41, 206);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4037, N'GARIB-E-NEWAZ ', 41, 106);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4019, N'GULSHAN ', 41, 233);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4161, N'HABIGONJ ', 41, 501);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4115, N'HATHAZARI ', 41, 32);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4003, N'IMAMGANJ ', 41, 14);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4017, N'ISLAMPUR ', 41, 237);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4044, N'JATRABARI ', 41, 114);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4214, N'JESSORE ', 41, 455);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4305, N'JHENAIDAH ', 41, 203);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4213, N'JHIKARGACHA ', 41, 26);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4012, N'JINJIRA ', 41, 201);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4014, N'JOYPARA ', 41, 321);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4126, N'JUBILEE ROAD ', 41, 37);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4009, N'KAKRAIL ', 41, 225);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4041, N'KALAMPUR ', 41, 105);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4043, N'KALATIA ', 41, 108);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4045, N'KAMRANGIR CHAR ', 41, 113);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4002, N'KARWAN BAZAR ', 41, 15);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4102, N'KHATUNGANJ ', 41, 2);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4301, N'KHULNA ', 41, 22);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4124, N'KHULSHI ', 41, 41);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4216, N'KUSHTIA ', 41, 502);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4210, N'LALMONIRHAT ', 41, 601);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4106, N'LOHAGARA ', 41, 6);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4040, N'MADHABDI ', 41, 361);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4120, N'MADHABPUR ', 41, 133);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4031, N'MALIBAGH ', 41, 241);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4015, N'MIRPUR ', 41, 231);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4011, N'MOHAKHALI ', 41, 230);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4140, N'MOMIN ROAD ', 41, 46);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4004, N'MOTIJHEEL ', 41, 16);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4116, N'MOULVIBAZAR ', 41, 10);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4030, N'MYMENSINGH ', 41, 331);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4203, N'NAOGAON ', 41, 632);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4008, N'NARAYANGONJ ', 41, 20);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4013, N'NAWABPUR ROAD', 41, 202);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4104, N'NAZU MEAH HAT ', 41, 4);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4006, N'NEW ELEPHANT ROAD ', 41, 17);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4010, N'NORTH SOUTH ROAD ', 41, 229);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4209, N'PABNA ', 41, 141);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4024, N'PAGLA ', 41, 19);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4121, N'PAHARTALI ', 41, 42);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4042, N'PARIL ', 41, 109);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4122, N'PATHERHAT', 41, 43);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4127, N'PORT CON. ROAD  ', 41, 40);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4005, N'PRINCIPAL ', 41, 18);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4028, N'PROGATI SHARANI ', 41, 238);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4202, N'RAJSHAHI ', 41, 60);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4205, N'RANGPUR ', 41, 692);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4022, N'ROKEYA SHARANI ', 41, 236);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4211, N'SAIDPUR ', 41, 50);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4138, N'SANDWIP ', 41, 45);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4212, N'SATKHIRA ', 41, 30);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4029, N'SAVAR ', 41, 239);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4035, N'SEED STORE ', 41, 104);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4032, N'SHAYMOLI ', 41, 240);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4207, N'SIRAJGANJ ', 41, 635);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4109, N'SITAKUNDA ', 41, 36);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4118, N'SREEMONGAL ', 41, 132);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4103, N'STATION ROAD ', 41, 3);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4117, N'TAJPUR ', 41, 205);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4036, N'TANGAIL ', 41, 325);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4128, N'TEKNAF ', 41, 86);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4038, N'TONGI ', 41, 110);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4020, N'UTTARA ', 41, 234);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4112, N'VIP ROAD ', 41, 9);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (7027, N'ISLAMI BANKING BRANCH', 41, 701);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4707, N'AGENT BANKING', 41, 18);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4001, N'HEAD OFFICE', 41, 101);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4070, N'FI AND TREASURY DIVISION', 41, NULL);
INSERT INTO Static_BB_BranchCode (BranchNumber, BranchName, FI_Code, FI_BranchCode) VALUES (4601, N'OBU', 41, 519);